---
plugin: community.general.proxmox
validate_certs: false
want_facts: true
groups:
  loadbalancers: "'loadbalancer' in (proxmox_tags_parsed | list)"
compose:
  ansible_user: ansible
  ansible_host: proxmox_ipconfig0.ip | ipaddr('address')
